### ISSUE TITLE
compute nodes wget call issue

### ISSUE THREAD

**Issue by rajeeja** [ECP-CANDLE/Supervisor#72]
Can we get rid of the import wget?:

It causes the following problem on summit:
Traceback (most recent call last):
  File "/gpfs/alpine/med106/scratch/jain/Supervisor/workflows/common/python/model_runner.py", line 326, in <module>
    run_model(hyper_parameter_map)
  File "/gpfs/alpine/med106/scratch/jain/Supervisor/workflows/common/python/model_runner.py", line 239, in run_model
    result, history = run(hyper_parameter_map, obj_return)
  File "/gpfs/alpine/med106/scratch/jain/Supervisor/workflows/common/python/model_runner.py", line 153, in run
    pkg = import_pkg(framework, model_name)
  File "/gpfs/alpine/med106/scratch/jain/Supervisor/workflows/common/python/model_runner.py", line 47, in import_pkg
    pkg = importlib.import_module(module_name)
  File "/ccs/proj/med106/hsyoo/summit/conda36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/alpine/med106/scratch/jain/Benchmarks/Pilot1/NT3/nt3_baseline_keras2.py", line 22, in <module>
    import nt3 as bmk
  File "/gpfs/alpine/med106/scratch/jain/Benchmarks/Pilot1/NT3/nt3.py", line 8, in <module>
    import candle
  File "/gpfs/alpine/med106/scratch/jain/Benchmarks/common/candle/__init__.py", line 6, in <module>
    from data_utils import load_csv_data
  File "/gpfs/alpine/med106/scratch/jain/Benchmarks/common/data_utils.py", line 17, in <module>
    from default_utils import DEFAULT_SEED
  File "/gpfs/alpine/med106/scratch/jain/Benchmarks/common/default_utils.py", line 26, in <module>
    from file_utils import get_file
  File "/gpfs/alpine/med106/scratch/jain/Benchmarks/common/file_utils.py", line 12, in <module>
    import wget
ModuleNotFoundError: No module named 'wget'

**Comment by jmohdyusof** [comment]
You made this issue in Supervisor but it actually pertains to Benchmarks?

**Comment by rajeeja** [comment]
oops, right!
